import * as THREE from '../node_modules/three/build/three.module.js';
import { Fly } from '../src/flymodel.js';
import { LIFSim, SpikeBus } from '../src/sim.js';
import { SignalBuilder } from '../src/signals.js';
import { angleDiff, clampf, lag } from '../src/util.js';
import { MATERIALS, PLACEABLES, PREDATOR_LEVELS, PREDATOR_SPECIES, WORLD_PRESETS, createWorldPreset, normalizeWorld, validateWorld, resizeWorld, placeAsset, removeAt, assetLabel, worldSummary, newEntityId } from '../src/worldstudio.js';
import { NeuralPolicyRuntime } from '../src/neuralrl.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)],CELL=26,TOP=88,BOTTOM=40,SPLIT=.68;
let world;try{const saved=JSON.parse(localStorage.getItem('desktopFly.openEcologyWorld.v1'));world=saved?normalizeWorld(saved):createWorldPreset('meadow');}catch{world=createWorldPreset('meadow');}
let paused=false,editing=false,selectedAsset='voxel:rock',selectedEntityId=null,followId=null,pendingModel=null,lastTime=performance.now(),simTime=0,toastTimer=0,kills=0,brainData=null;
const flies=[],predators=[],foods=[],staticGroup=new THREE.Group(),entityGroup=new THREE.Group(),deployedPolicies=new Map();

const scene=new THREE.Scene();scene.background=new THREE.Color(0x263f29);scene.fog=new THREE.FogExp2(0x263f29,.0013);scene.add(staticGroup,entityGroup);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.setScissorTest(true);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;renderer.shadowMap.enabled=true;document.body.prepend(renderer.domElement);
const sun=new THREE.DirectionalLight(0xfff1cf,2.25);sun.position.set(-300,-420,620);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun,new THREE.HemisphereLight(0xe9f7ff,0x2e4d28,1.9));
const mainCamera=new THREE.PerspectiveCamera(43,1,1,3000),eyeCamera=new THREE.PerspectiveCamera(105,1,.5,1200);let overviewZoom=1,overviewYaw=0,overviewPitch=.66;const overviewTarget=new THREE.Vector3(0,0,CELL),worldPointer={active:false};
renderer.domElement.dataset.worldNavigation='drag-orbit-zoom';renderer.domElement.dataset.predatorMotion='autonomous-collision';

const materialCache=new Map();function material(id){if(!materialCache.has(id)){const s=MATERIALS[id];materialCache.set(id,new THREE.MeshStandardMaterial({color:s.color,roughness:id==='water' ? .2 : .86,transparent:!s.solid,opacity:s.solid ? .96 : .7,emissive:(s.food||s.safe) ? s.color : 0,emissiveIntensity:(s.food||s.safe) ? .55 : 0}));}return materialCache.get(id);}
function clear(group){while(group.children.length){const child=group.children[0];group.remove(child);child.traverse?.(n=>n.geometry?.dispose?.());}}
const cellToScene=p=>new THREE.Vector3((p.x-(world.size.x-1)/2)*CELL,(p.y-(world.size.y-1)/2)*CELL,p.z*CELL);
function sceneToCell(x,y,z=1){const p={x:Math.round(x/CELL+(world.size.x-1)/2),y:Math.round(y/CELL+(world.size.y-1)/2),z:Math.round(z)};return p.x>=0&&p.y>=0&&p.z>=0&&p.x<world.size.x&&p.y<world.size.y&&p.z<world.size.z?p:null;}
const solidKeys=()=>new Set(world.voxels.filter(v=>MATERIALS[v[3]].solid).map(v=>`${v[0]},${v[1]},${v[2]}`));let solids=solidKeys();
function hitsSolid(x,y,z=1){const p=sceneToCell(x,y,z);return !p||solids.has(`${p.x},${p.y},${p.z}`);}
function modelForEntity(item){const group=new THREE.Group();let node;if(item.type==='spawn'){node=new THREE.Mesh(new THREE.RingGeometry(8,11,28),new THREE.MeshBasicMaterial({color:0x65e3de,side:THREE.DoubleSide}));}else if(item.type==='goal'){node=new THREE.Mesh(new THREE.TorusGeometry(10,2.4,8,28),new THREE.MeshStandardMaterial({color:0xe8f365,emissive:0x718c14,emissiveIntensity:1.4}));node.rotation.x=Math.PI/2;}else if(item.type==='food'){node=new THREE.Mesh(new THREE.SphereGeometry(item.kind==='sugar'?7:10,16,12),new THREE.MeshStandardMaterial({color:item.kind==='apple'?0xd54b3e:item.kind==='banana'?0xefca43:0xe49c35,roughness:.6}));node.scale.set(item.kind==='banana'?1.5:1,1,item.kind==='sugar'?.45:1);}else{const color=item.kind==='frog'?0x6da348:item.kind==='spider'?0x704735:0x89ae43;node=new THREE.Mesh(item.kind==='spider'?new THREE.SphereGeometry(12,16,12):new THREE.CapsuleGeometry(7,item.kind==='frog'?18:25,6,12),new THREE.MeshStandardMaterial({color,roughness:.7}));node.rotation.x=Math.PI/2;if(item.kind==='frog')node.scale.set(1.45,1,.7);for(let i=0;i<(item.kind==='spider'?8:4);i++){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(1,18,4,7),new THREE.MeshStandardMaterial({color}));leg.rotation.z=(i/(item.kind==='spider'?8:4))*Math.PI;group.add(leg);}}group.add(node);group.userData.entityId=item.id;group.traverse(n=>n.userData.entityId=item.id);return group;}
function markSelected(){for(const child of entityGroup.children){const selected=child.userData.entityId===selectedEntityId;child.traverse(part=>{if(part.material?.emissive){part.material.emissive.setHex(selected?0x245b16:0);part.material.emissiveIntensity=selected?.7:0;}});}}

function attachBrain(actor){if(!brainData||actor.brain)return;actor.bus=new SpikeBus();actor.brain=new LIFSim(brainData.circuit,actor.bus,brainData.locomotor);actor.builder=new SignalBuilder();actor.brainMs=0;actor.spikes=[];}
function attachNeuralPolicy(actor,manifest){const runtime=new NeuralPolicyRuntime(manifest,brainData);actor.policy=runtime;actor.manifest=manifest;actor.bus=runtime.bus;actor.brain=runtime.sim;actor.builder=runtime.builder;actor.brainMs=0;actor.spikes=[];actor.policySignals=null;actor.policyTimer=0;actor.policySteps=0;actor.lastAction='等待第一次下降神经元决策';}
function makeFly(item){const p=cellToScene(item.position),fly=new Fly({x:p.x,y:p.y});fly.node.position.z=Math.max(0,(item.position.z-1)*CELL);fly.node.traverse(part=>{if(part.isMesh)part.castShadow=true;});fly.node.userData.entityId=item.id;fly.node.traverse(n=>n.userData.entityId=item.id);entityGroup.add(fly.node);const actor={id:item.id,source:item,fly,node:fly.node,brain:null,policy:null,manifest:null,policyTimer:0,policySteps:0,lastAction:'',danger:null,food:null,feeding:0,webTimer:0},saved=deployedPolicies.get(item.id);if(saved)try{attachNeuralPolicy(actor,saved);}catch{deployedPolicies.delete(item.id);}flies.push(actor);attachBrain(actor);}
function makePredator(item){const node=modelForEntity(item),p=cellToScene(item.position);node.position.set(p.x,p.y,Math.max(0,(item.position.z-1)*CELL));entityGroup.add(node);predators.push({id:item.id,source:item,node,kind:item.kind,level:item.level,profile:PREDATOR_LEVELS[item.level],x:p.x,y:p.y,z:item.position.z,heading:Math.random()*Math.PI*2,phase:Math.random()*5,cooldown:Math.random()*2,ambush:false});}
function makeFood(item){const node=modelForEntity(item),p=cellToScene(item.position);node.position.set(p.x,p.y,Math.max(3,(item.position.z-1)*CELL+6));entityGroup.add(node);foods.push({id:item.id,source:item,node,kind:item.kind,x:p.x,y:p.y,amount:1});}
function saveWorld(){localStorage.setItem('desktopFly.openEcologyWorld.v1',JSON.stringify(world));}
function rebuildWorld({resetActors=true}={}){clear(staticGroup);if(resetActors){clear(entityGroup);flies.length=predators.length=foods.length=0;}solids=solidKeys();for(const [x,y,z,id] of world.voxels){const s=MATERIALS[id],mesh=new THREE.Mesh(s.solid?new THREE.BoxGeometry(CELL*.96,CELL*.96,CELL*.96):new THREE.CylinderGeometry(CELL*.3,CELL*.38,CELL*.12,18),material(id)),p=cellToScene({x,y,z});mesh.position.set(p.x,p.y,p.z+(s.solid?CELL*.48:CELL*.1));mesh.castShadow=s.solid;mesh.receiveShadow=true;staticGroup.add(mesh);}if(resetActors){for(const item of world.entities.filter(v=>v.enabled)){if(item.type==='spawn')makeFly(item);else if(item.type==='predator')makePredator(item);else if(item.type==='food')makeFood(item);else{const node=modelForEntity(item),p=cellToScene(item.position);node.position.set(p.x,p.y,p.z+5);entityGroup.add(node);}}if(!flies.length){const item={id:newEntityId('spawn'),type:'spawn',kind:'fly',position:{x:2,y:2,z:1},enabled:true};world.entities.push(item);makeFly(item);}followId=flies.some(v=>v.id===followId)?followId:flies[0].id;}refreshUI();}

// Neural view belongs to the same actor as the first-person camera.
const brainCanvas=$('#brainCanvas'),brainRenderer=new THREE.WebGLRenderer({canvas:brainCanvas,antialias:true,alpha:true});brainRenderer.setPixelRatio(Math.min(devicePixelRatio,2));brainRenderer.outputColorSpace=THREE.SRGBColorSpace;const brainScene=new THREE.Scene(),brainCamera=new THREE.PerspectiveCamera(38,1,.1,100),brainGroup=new THREE.Group();brainCamera.position.z=13;brainScene.add(brainGroup,new THREE.AmbientLight(0x70a9c0,.7));let brainPoints,baseColors,colors,glow;
const roleColors={lc4:[.2,.85,1],lplc2:[.2,.85,1],gf:[1,.82,.15],dna01:[1,.45,.12],dna02:[1,.45,.12],mdn:[.72,.35,1],dnp09:[.3,1,.55],dng11:[1,.42,.72],escw:[1,.74,.2],other:[.18,.34,.48]};
function buildBrain(circuit){clear(brainGroup);const raw=circuit.neurons.map(n=>n.pos?.length===3?n.pos:[0,0,0]),center=[0,1,2].map(a=>raw.reduce((s,p)=>s+p[a],0)/raw.length);let radius=1;for(const p of raw)radius=Math.max(radius,Math.hypot(p[0]-center[0],p[1]-center[1],p[2]-center[2]));const positions=new Float32Array(raw.length*3);baseColors=new Float32Array(raw.length*3);colors=new Float32Array(raw.length*3);glow=new Float32Array(raw.length);circuit.neurons.forEach((n,i)=>{positions[3*i]=(raw[i][0]-center[0])/radius*4.3;positions[3*i+1]=(raw[i][1]-center[1])/radius*4.3;positions[3*i+2]=(raw[i][2]-center[2])/radius*4.3;const c=roleColors[n.role]||roleColors.other;baseColors.set(c,3*i);colors.set(c,3*i);});const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));brainPoints=new THREE.Points(geometry,new THREE.PointsMaterial({size:.095,vertexColors:true,transparent:true,opacity:.9,blending:THREE.AdditiveBlending,depthWrite:false}));brainGroup.add(brainPoints);$('#brainSync').textContent=`${raw.length} 神经元 · 与第一视角同步`;$('#brainPanel').dataset.neuronCount=String(raw.length);$('#brainPanel').dataset.source='followedFly';}
const followed=()=>flies.find(v=>v.id===followId)||flies[0];
function nearest(list,x,y){let item=null,d=Infinity;for(const v of list){const n=Math.hypot(v.x-x,v.y-y);if(n<d){d=n;item=v;}}return{item,d};}
function updateBrain(actor,dt){attachBrain(actor);if(!actor?.brain)return null;const threat=nearest(predators,actor.fly.pos.x,actor.fly.pos.y),strength=threat.item?clampf(1-threat.d/(threat.item.profile.vision*CELL),0,1):0;actor.brain.loomL=strength*.5;actor.brain.loomR=strength*.5;actor.brain.airPuff=threat.d<CELL*2?1-threat.d/(CELL*2):0;actor.brain.gaitDrive=actor.fly.walkingIntensity||0;actor.brain.gaitPhase=actor.fly.gaitPhasePublic||0;actor.brain.legFeedback=actor.fly.legFeedback||[];actor.brainMs+=dt*1000;const steps=Math.min(50,Math.floor(actor.brainMs));actor.brainMs-=steps;actor.brain.step(steps);actor.spikes=actor.bus.popAll();return actor.builder.make(actor.brain,dt);}
function renderBrain(dt){const rect=$('#brainPanel').getBoundingClientRect(),w=Math.max(1,rect.width),h=Math.max(1,rect.height);if(brainCanvas.width!==Math.round(w*brainRenderer.getPixelRatio())||brainCanvas.height!==Math.round(h*brainRenderer.getPixelRatio())){brainRenderer.setSize(w,h,false);brainCamera.aspect=w/h;brainCamera.updateProjectionMatrix();}const actor=followed();if(actor?.brain&&brainPoints){for(const e of actor.spikes||[])if(e.neuron<glow.length)glow[e.neuron]=e.isGF?1.8:1;for(let i=0;i<glow.length;i++){glow[i]*=Math.exp(-dt*6);colors[3*i]=Math.min(1,baseColors[3*i]+glow[i]);colors[3*i+1]=Math.min(1,baseColors[3*i+1]+glow[i]*.8);colors[3*i+2]=Math.min(1,baseColors[3*i+2]+glow[i]*.45);}brainPoints.geometry.attributes.color.needsUpdate=true;brainGroup.rotation.y+=dt*.2;$('#ratePop').textContent=actor.brain.ratePop.toFixed(1);$('#rateLoom').textContent=actor.brain.rateLoom.toFixed(1);$('#rateForward').textContent=actor.brain.rateFwd.toFixed(1);$('#rateEscape').textContent=actor.brain.rateEscW.toFixed(1);$('#brainFlyName').textContent=`${flies.indexOf(actor)+1}号果蝇${actor.manifest?` · ${actor.manifest.modelId||'旧版无编号'}`:' · 未部署模型'}`;$('#brainPanel').dataset.simMs=String(actor.brain.simMs);}brainRenderer.render(brainScene,brainCamera);}

function removeFlyActor(actor){entityGroup.remove(actor.node);const index=flies.indexOf(actor);if(index>=0)flies.splice(index,1);world.entities=world.entities.filter(v=>v.id!==actor.id);deployedPolicies.delete(actor.id);if(followId===actor.id)followId=flies[0]?.id;saveWorld();refreshUI();}
function predatorAttack(predator,target){if(predator.cooldown>0||!target)return;const multiplier=predator.kind==='frog'?1.65:predator.kind==='mantis'?1.25:1,reach=predator.profile.reach*CELL*multiplier;if(Math.hypot(target.fly.pos.x-predator.x,target.fly.pos.y-predator.y)>reach)return;predator.cooldown=predator.profile.cooldown;if(Math.random()>predator.profile.captureChance)return;const number=flies.indexOf(target)+1;removeFlyActor(target);kills++;toast(`${PREDATOR_LEVELS[predator.level].name}${PREDATOR_SPECIES[predator.kind].name}捕获了 ${number} 号果蝇`);}
function updatePredators(dt){let travel=0;for(const p of predators){p.phase+=dt;p.cooldown-=dt;const beforeX=p.x,beforeY=p.y,target=nearest(flies.map(actor=>({x:actor.fly.pos.x,y:actor.fly.pos.y,actor})),p.x,p.y);p.ambush=p.kind==='spider'&&target.d>CELL*3&&Math.sin(p.phase*1.5)>.1;if(target.item&&target.d<p.profile.vision*CELL){const desired=Math.atan2(target.item.y-p.y,target.item.x-p.x);p.heading+=angleDiff(p.heading,desired)*lag(4,dt);const leap=p.kind==='frog'&&Math.sin(p.phase*1.6)>.72,speed=p.profile.speed*CELL*(leap?2:p.ambush?0:1),nx=p.x+Math.cos(p.heading)*speed*dt,ny=p.y+Math.sin(p.heading)*speed*dt;if(!hitsSolid(nx,ny,p.z)){p.x=nx;p.y=ny;}else p.heading+=Math.PI*.7;predatorAttack(p,target.item.actor);}else{p.heading+=Math.sin(p.phase)*.005;const nx=p.x+Math.cos(p.heading)*p.profile.speed*CELL*.12*dt,ny=p.y+Math.sin(p.heading)*p.profile.speed*CELL*.12*dt;if(!hitsSolid(nx,ny,p.z)){p.x=nx;p.y=ny;}}travel+=Math.hypot(p.x-beforeX,p.y-beforeY);p.node.position.x=p.x;p.node.position.y=p.y;p.node.rotation.z=p.heading;}renderer.domElement.dataset.predatorTravel=String(Number(renderer.domElement.dataset.predatorTravel||0)+travel);}
function policyObservation(actor){const p=sceneToCell(actor.fly.pos.x,actor.fly.pos.y,Math.max(1,Math.round((actor.fly.node.position.z||0)/CELL)+1))||{x:0,y:0,z:1};return{position:p,heading:actor.fly.heading,step:Math.floor(simTime*10),energy:1,gaitDrive:actor.fly.walkingIntensity||0,gaitPhase:actor.fly.gaitPhasePublic||0,legFeedback:actor.fly.legFeedback||[],food:foods.map(v=>({position:sceneToCell(v.x,v.y,1)||{x:0,y:0,z:1}})),predators:predators.map(v=>({position:sceneToCell(v.x,v.y,v.z)||{x:0,y:0,z:v.z},level:v.level}))};}
function applyPolicy(actor,dt){if(!actor.policy)return null;actor.policyTimer-=dt;if(actor.policyTimer>0){actor.spikes=[];return actor.policySignals;}actor.policyTimer=Math.max(.035,.16/Number(actor.manifest.traits?.intelligence||1));const result=actor.policy.step(policyObservation(actor),actor.policyTimer);actor.policySteps++;actor.policySignals=result.signals;actor.spikes=result.spikes;actor.lastAction=`${result.action.name}（下降神经元输出）`;return result.signals;}
function updateFlies(dt){const bounds={width:world.size.x*CELL,height:world.size.y*CELL};for(const actor of [...flies]){const fly=actor.fly,threat=nearest(predators,fly.pos.x,fly.pos.y),food=nearest(foods,fly.pos.x,fly.pos.y),sensitivity=Number(actor.manifest?.traits?.escapeSensitivity||1),stealth=threat.item?.kind==='mantis'&&threat.d>CELL*5?.5:threat.item?.ambush?.5:1;actor.danger=threat.item&&threat.d<threat.item.profile.vision*CELL*sensitivity*stealth?threat.item:null;actor.food=!actor.danger&&food.d<CELL*9?food.item:null;let signals;if(actor.policy){signals=applyPolicy(actor,dt);}else{signals=updateBrain(actor,dt);if(actor.danger&&fly.state!=='flying'&&fly.scareCooldown<=0)fly.startFlight(bounds,{awayFrom:{x:actor.danger.x,y:actor.danger.y},escape:true});else if(actor.food&&fly.state!=='flying'){const desired=Math.atan2(actor.food.y-fly.pos.y,actor.food.x-fly.pos.x);fly.heading+=angleDiff(fly.heading,desired)*lag(3,dt);if(food.d<CELL*.65){actor.feeding+=dt;fly.speed=0;actor.food.amount-=dt*.3;if(actor.food.amount<=0){entityGroup.remove(actor.food.node);foods.splice(foods.indexOf(actor.food),1);world.entities=world.entities.filter(v=>v.id!==actor.food.id);saveWorld();}}else{actor.feeding=0;if(fly.state!=='walking')fly.setState('walking');fly.speed=Math.max(fly.speed,32);}}}if(actor.webTimer>0){actor.webTimer-=dt;fly.speed*=.55;}if(threat.item?.kind==='spider'&&threat.d<CELL*3)actor.webTimer=.7;const before={x:fly.pos.x,y:fly.pos.y};fly.update(dt,bounds,actor.danger?{x:actor.danger.x,y:actor.danger.y}:null,signals);const z=Math.max(1,Math.round((fly.node.position.z||0)/CELL)+1);if(hitsSolid(fly.pos.x,fly.pos.y,z)){fly.pos.x=before.x;fly.pos.y=before.y;fly.node.position.x=before.x;fly.node.position.y=before.y;fly.heading+=Math.PI*.72;fly.speed*=.2;}}}
function cameras(){const h=Math.max(1,innerHeight-TOP-BOTTOM),mainW=Math.floor(innerWidth*SPLIT),eyeH=Math.floor(h*.48);mainCamera.aspect=mainW/h;const span=Math.max(world.size.x,world.size.y)*CELL,radius=span*1.17*overviewZoom,cp=Math.cos(overviewPitch);mainCamera.position.set(overviewTarget.x+Math.sin(overviewYaw)*cp*radius,overviewTarget.y-Math.cos(overviewYaw)*cp*radius,overviewTarget.z+Math.sin(overviewPitch)*radius);mainCamera.up.set(0,0,1);mainCamera.lookAt(overviewTarget);mainCamera.updateProjectionMatrix();const actor=followed();if(actor){const fly=actor.fly,forward=new THREE.Vector3(Math.cos(fly.heading),Math.sin(fly.heading),0),target=new THREE.Vector3(fly.pos.x,fly.pos.y,8+(fly.node.position.z||0));eyeCamera.position.lerp(target.clone().addScaledVector(forward,18).add(new THREE.Vector3(0,0,6)),.23);eyeCamera.up.set(0,0,1);eyeCamera.lookAt(target.clone().addScaledVector(forward,120));eyeCamera.aspect=Math.max(1,innerWidth-mainW)/eyeH;eyeCamera.updateProjectionMatrix();}}
function renderViews(){const width=innerWidth,height=innerHeight,h=height-TOP-BOTTOM,mainW=Math.floor(width*SPLIT),eyeH=Math.floor(h*.48),eyeBottom=BOTTOM+h-eyeH;renderer.setScissor(0,BOTTOM,mainW,h);renderer.setViewport(0,BOTTOM,mainW,h);renderer.setClearColor(0x263f29);renderer.render(scene,mainCamera);renderer.setScissor(mainW,eyeBottom,width-mainW,eyeH);renderer.setViewport(mainW,eyeBottom,width-mainW,eyeH);renderer.setClearColor(0x253c28);renderer.render(scene,eyeCamera);}
function thought(){const actor=followed();if(!actor)return['场地中没有果蝇。','请添加果蝇出生点。'];if(actor.manifest)return[`神经模型 ${actor.manifest.modelId||'旧版无编号'}：${actor.lastAction||'读取感觉输入'}。`,`环境感觉 → FlyWire ${actor.manifest.brain?.neuronCount||668} 神经元 → 下降神经元 → MaleCNS；已决策 ${actor.policySteps} 次`];if(actor.danger)return[`检测到${PREDATOR_LEVELS[actor.danger.level].name}${PREDATOR_SPECIES[actor.danger.kind].name}，基础神经回路产生逃生反应。`,`视野 ${actor.danger.profile.vision} 格 · 速度 ${actor.danger.profile.speed} 格/秒`];if(actor.food)return[`发现${assetLabel(actor.food.source)}，正在循味接近。`,`距离 ${Math.round(Math.hypot(actor.food.x-actor.fly.pos.x,actor.food.y-actor.fly.pos.y)/CELL)} 格`];return['正在自由探索大型三维生态空间。','未部署训练模型 · 使用基础 FlyWire / MaleCNS 神经行为'];}
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.04,Math.max(0,(now-lastTime)/1000));lastTime=now;if(!paused){simTime+=dt;updatePredators(dt);updateFlies(dt);}cameras();renderViews();renderBrain(dt);const t=thought();$('#thoughtText').textContent=t[0];$('#thoughtReason').textContent=t[1];if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('#toast').classList.remove('show');}refreshCounts();}

function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');toastTimer=2;}
function refreshCounts(){$('#flyCount').textContent=flies.length;$('#predatorCount').textContent=predators.length;$('#foodCount').textContent=foods.length;$('#killCount').textContent=kills;if($('#deploymentRuntime')){const active=flies.filter(actor=>actor.manifest);$('#deploymentRuntime').innerHTML=active.length?`<b>模型运行中</b><br>${active.map(actor=>`${flies.indexOf(actor)+1}号果蝇 · ${actor.manifest.modelId||'旧版无编号'} · 已决策 ${actor.policySteps} 次 · ${actor.lastAction||'正在读取观测'}`).join('<br>')}`:'<b>尚未部署</b><br>选择模型文件或接收训练页模型，然后指定果蝇。';}}
function refreshFlySelect(){for(const id of ['#followFly','#deployFly']){const select=$(id),value=select.value;select.replaceChildren(...flies.map((actor,index)=>new Option(`${index+1}号 · ${actor.manifest?`已部署 ${actor.manifest.modelId||'旧版无编号'}`:'未部署'}`,actor.id)));if(flies.some(v=>v.id===value))select.value=value;}$('#followFly').value=followId||'';}
function predatorInfo(){const level=PREDATOR_LEVELS[$('#predatorLevel').value];$('#predatorInfo').innerHTML=`<b>${level.name}天敌：${level.description}</b><br>速度 ${level.speed} 格/秒 · 视野 ${level.vision} 格 · 攻击距离 ${level.reach} 格 · 冷却 ${level.cooldown} 秒 · 捕获概率 ${Math.round(level.captureChance*100)}%<br><span class="skill">${Object.values(PREDATOR_SPECIES).map(s=>`${s.name}技能：${s.skills.map(v=>v.name).join('、')}`).join('<br>')}</span>`;}
function refreshEntities(){$('#entityList').replaceChildren(...world.entities.map(item=>{const row=document.createElement('div');row.className='entity-row';row.innerHTML=`<span>${assetLabel(item)} · (${item.position.x},${item.position.y},${item.position.z})</span><button data-id="${item.id}">删除</button>`;row.querySelector('button').onclick=()=>{world=removeAt(world,null,{entityId:item.id});saveWorld();rebuildWorld();toast('对象已删除');};return row;}));}
function refreshUI(){$('#sizeX').value=world.size.x;$('#sizeY').value=world.size.y;$('#sizeZ').value=world.size.z;$('#editLayer').max=world.size.z-1;$('#editLayer').value=Math.min(Number($('#editLayer').value),world.size.z-1);$('#layerValue').textContent=$('#editLayer').value;refreshFlySelect();refreshEntities();refreshCounts();$('#statusMessage').textContent=worldSummary(world);markSelected();}
for(const preset of WORLD_PRESETS)$('#presetSelect').add(new Option(preset.name,preset.id));$('#presetSelect').value=world.preset==='custom'?'meadow':world.preset;
function renderPalette(){$('#palette').replaceChildren(...PLACEABLES.map(asset=>{const b=document.createElement('button');b.textContent=asset.name;b.classList.toggle('active',selectedAsset===asset.id);b.onclick=()=>{selectedAsset=asset.id;renderPalette();};return b;}),(()=>{const b=document.createElement('button');b.textContent='删除格内全部';b.classList.toggle('active',selectedAsset==='erase');b.onclick=()=>{selectedAsset='erase';renderPalette();};return b;})());}

const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();function inWorldView(event){return event.clientX<=innerWidth*SPLIT&&event.clientY>=TOP&&event.clientY<=innerHeight-BOTTOM;}function setRay(event){const mainW=innerWidth*SPLIT,h=innerHeight-TOP-BOTTOM;pointer.set(event.clientX/mainW*2-1,-((event.clientY-TOP)/h)*2+1);raycaster.setFromCamera(pointer,mainCamera);}function applyWorldClick(event){setRay(event);if(editing){const z=Number($('#editLayer').value),hit=new THREE.Vector3();if(raycaster.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,0,1),-z*CELL),hit)){const p=sceneToCell(hit.x,hit.y,z);if(p){world=selectedAsset==='erase'?removeAt(world,p):placeAsset(world,selectedAsset,p,{predatorLevel:$('#predatorLevel').value,singleSpawn:false});saveWorld();rebuildWorld();toast('世界已更新');}}return;}const hit=raycaster.intersectObjects(entityGroup.children,true).find(v=>v.object.userData.entityId);selectedEntityId=hit?.object.userData.entityId||null;markSelected();if(selectedEntityId)toast(`已选择 ${assetLabel(world.entities.find(v=>v.id===selectedEntityId))}`);}
renderer.domElement.addEventListener('contextmenu',event=>event.preventDefault());renderer.domElement.addEventListener('pointerdown',event=>{if(!inWorldView(event))return;worldPointer.active=true;worldPointer.id=event.pointerId;worldPointer.button=event.button;worldPointer.x=event.clientX;worldPointer.y=event.clientY;worldPointer.moved=false;renderer.domElement.setPointerCapture(event.pointerId);});renderer.domElement.addEventListener('pointermove',event=>{if(!worldPointer.active)return;if(Math.hypot(event.clientX-worldPointer.x,event.clientY-worldPointer.y)>4)worldPointer.moved=true;if(worldPointer.button===2){overviewYaw-=event.movementX*.008;overviewPitch=clampf(overviewPitch+event.movementY*.006,.2,1.35);}else if(worldPointer.button===1||(worldPointer.button===0&&!editing)){const scale=Math.max(world.size.x,world.size.y)*CELL*overviewZoom*.0018,right=new THREE.Vector3(Math.cos(overviewYaw),Math.sin(overviewYaw),0),forward=new THREE.Vector3(-Math.sin(overviewYaw),Math.cos(overviewYaw),0);overviewTarget.addScaledVector(right,-event.movementX*scale).addScaledVector(forward,event.movementY*scale);}});renderer.domElement.addEventListener('pointerup',event=>{if(worldPointer.active&&worldPointer.button===0&&!worldPointer.moved)applyWorldClick(event);worldPointer.active=false;});renderer.domElement.addEventListener('pointercancel',()=>worldPointer.active=false);renderer.domElement.addEventListener('wheel',event=>{if(inWorldView(event)){event.preventDefault();overviewZoom=clampf(overviewZoom+Math.sign(event.deltaY)*.08,.42,1.8);}},{passive:false});
$('#editorBtn').onclick=()=>{$('#drawer').classList.add('show');};$('#closeDrawer').onclick=()=>$('#drawer').classList.remove('show');$('#editToggle').onclick=e=>{editing=!editing;e.currentTarget.classList.toggle('active',editing);e.currentTarget.textContent=editing?'结束放置素材':'开始放置素材';paused=editing;$('#runState').textContent=editing?'编辑中':'运行中';};$('#editLayer').oninput=()=>{$('#layerValue').textContent=$('#editLayer').value;if($('#ecoExactZ'))$('#ecoExactZ').value=$('#editLayer').value;};$('#predatorLevel').onchange=predatorInfo;
$('#loadPreset').onclick=()=>{world=createWorldPreset($('#presetSelect').value);selectedEntityId=null;kills=0;saveWorld();rebuildWorld();toast('已载入大型地图预设，所有内容仍可编辑');};$('#applySize').onclick=()=>{world=resizeWorld(world,{x:Number($('#sizeX').value),y:Number($('#sizeY').value),z:Number($('#sizeZ').value)});saveWorld();rebuildWorld();};$('#saveWorld').onclick=()=>{saveWorld();toast('世界已保存到本机');};function download(value,name){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}$('#exportWorld').onclick=()=>download(world,`${world.name}.world.json`);
$('#importWorld').onclick=()=>$('#worldFile').click();$('#worldFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const value=JSON.parse(await file.text()),check=validateWorld(value.world||value);if(!check.valid)throw new Error(check.errors.join('；'));world=check.world;saveWorld();rebuildWorld();toast('世界工程导入成功');}catch(error){$('#modelStatus').textContent=`导入失败：${error.message}`;}e.target.value='';};
function acceptModel(value,source='模型文件'){if(value?.kind!=='desktop-fly-neural-rl-policy'||!value.world||!value.experiment||!value.policy||!value.plasticity||!value.brain)throw new Error('请选择由连接组训练页导出的完整神经强化学习模型；旧式 Q 表策略不能部署为果蝇大脑');pendingModel=value;$('#deployModel').disabled=false;$('#syncModelWorld').disabled=false;const quality=Math.round(Number(value.metrics?.successRate||value.metrics?.recentSuccess||0)*100);$('#modelStatus').textContent=`✅ ${source}已载入：神经模型 ${value.modelId||'旧版无编号'} · ${value.brain.neuronCount} 神经元/${value.brain.edgeCount} 突触 · ${value.plasticity.changedGroupEdges} 组突触已改变 · 成功率 ${quality}%。请选择果蝇。`;$('#drawer').classList.add('show');}
async function loadLatestPolicy(){try{const value=await window.flyAPI.getLatestOpenPolicy();if(value)acceptModel(value,'训练页最新模型');}catch(error){$('#modelStatus').textContent=`读取应用模型仓库失败：${error.message}`;}}
$('#chooseModel').onclick=()=>$('#modelFile').click();$('#quickChooseModel').onclick=()=>{$('#drawer').classList.add('show');$('#modelFile').click();};$('#modelFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{acceptModel(JSON.parse(await file.text()),'导出模型文件');}catch(error){pendingModel=null;$('#deployModel').disabled=true;$('#syncModelWorld').disabled=true;$('#modelStatus').textContent=`载入失败：${error.message}`;}e.target.value='';};$('#deployModel').onclick=()=>{const actor=flies.find(v=>v.id===$('#deployFly').value);if(!actor||!pendingModel){$('#modelStatus').textContent='请先载入模型并选择一只果蝇。';return;}try{attachNeuralPolicy(actor,pendingModel);deployedPolicies.set(actor.id,pendingModel);refreshFlySelect();followId=actor.id;$('#followFly').value=actor.id;paused=false;editing=false;$('#pauseBtn').textContent='⏸ 暂停';$('#editToggle').classList.remove('active');$('#editToggle').textContent='开始放置素材';$('#runState').textContent='运行中';const p=actor.policy.plasticitySummary;$('#modelStatus').textContent=`✅ 神经模型 ${pendingModel.modelId||'旧版无编号'} 已部署到 ${flies.indexOf(actor)+1} 号果蝇：${p.changed}/${p.edgeCount} 条 LIF 突触应用了学习增益。动作现在只经下降神经元和 MaleCNS 输出。`;toast('神经模型已映射到指定果蝇大脑');}catch(error){$('#modelStatus').textContent=`部署失败：${error.message}`;}};
$('#followFly').onchange=()=>{followId=$('#followFly').value;};$('#addFly').onclick=()=>{const p={x:2+flies.length%Math.max(2,world.size.x-4),y:2,z:1};world.entities.push({id:newEntityId('spawn'),type:'spawn',kind:'fly',position:p,enabled:true});saveWorld();rebuildWorld();};$('#pauseBtn').onclick=e=>{paused=!paused;e.currentTarget.textContent=paused?'▶ 继续':'⏸ 暂停';$('#runState').textContent=paused?'已暂停':'运行中';};$('#deleteSelected').onclick=()=>{if(!selectedEntityId){toast('请先在全景中点击天敌、食物、目标或果蝇');return;}world=removeAt(world,null,{entityId:selectedEntityId});selectedEntityId=null;saveWorld();rebuildWorld();toast('选中对象已删除');};$('#openTraining').onclick=()=>window.flyAPI.showWindow('training');addEventListener('resize',()=>renderer.setSize(innerWidth,innerHeight));

async function start(){try{brainData=await window.flyAPI.getBrainData();if(brainData?.circuit)buildBrain(brainData.circuit);}catch(error){$('#brainSync').textContent=`大脑加载失败：${error.message}`;}rebuildWorld();for(const actor of flies)attachBrain(actor);await loadLatestPolicy();requestAnimationFrame(frame);}
const exactPlacement=document.createElement('div');exactPlacement.className='field';exactPlacement.innerHTML='<label>精确坐标放置（所有素材支持高度 Z）</label><div class="grid3"><input id="ecoExactX" type="number" min="0" value="2" aria-label="放置X"><input id="ecoExactY" type="number" min="0" value="2" aria-label="放置Y"><input id="ecoExactZ" type="number" min="0" value="1" aria-label="放置Z"></div><button id="ecoPlaceExact" style="width:100%;margin-top:6px">放置当前素材到 X / Y / Z</button>';$('#predatorLevel').closest('.field').before(exactPlacement);$('#ecoPlaceExact').onclick=()=>{if(!selectedAsset||selectedAsset==='erase'){toast('请先选择要放置的素材');return;}const p={x:Number($('#ecoExactX').value),y:Number($('#ecoExactY').value),z:Number($('#ecoExactZ').value)};if(!Number.isInteger(p.x)||!Number.isInteger(p.y)||!Number.isInteger(p.z)||p.x<0||p.y<0||p.z<0||p.x>=world.size.x||p.y>=world.size.y||p.z>=world.size.z){$('#modelStatus').textContent=`坐标超出范围：X 0–${world.size.x-1}，Y 0–${world.size.y-1}，Z 0–${world.size.z-1}。`;return;}const next=placeAsset(world,selectedAsset,p,{predatorLevel:$('#predatorLevel').value,singleSpawn:false}),check=validateWorld(next);if(!check.valid){$('#modelStatus').textContent=`不能放置：${check.errors.join('；')}`;return;}world=next;saveWorld();rebuildWorld();$('#editLayer').value=p.z;$('#editLayer').dispatchEvent(new Event('input'));toast(`素材已放到 (${p.x}, ${p.y}, ${p.z})`);};
const deploymentRuntime=document.createElement('div');deploymentRuntime.id='deploymentRuntime';deploymentRuntime.className='info';deploymentRuntime.innerHTML='<b>尚未部署</b><br>选择模型文件或接收训练页模型，然后指定果蝇。';$('#modelStatus').after(deploymentRuntime);
const syncModelWorld=document.createElement('button');syncModelWorld.id='syncModelWorld';syncModelWorld.textContent='载入该模型的训练场景';syncModelWorld.disabled=true;$('#deployModel').before(syncModelWorld);syncModelWorld.onclick=()=>{if(!pendingModel)return;world=normalizeWorld(pendingModel.world);deployedPolicies.clear();selectedEntityId=null;kills=0;saveWorld();rebuildWorld();$('#presetSelect').value=WORLD_PRESETS.some(item=>item.id===world.preset)?world.preset:'meadow';$('#modelStatus').textContent=`已切换到模型 ${pendingModel.modelId||'旧版无编号'} 的训练场景。现在选择果蝇并点击部署。`;toast('训练场景已同步到生态空间');};window.flyAPI.onOpenPolicyAvailable(value=>{try{acceptModel(value,'训练页最新模型');}catch(error){$('#modelStatus').textContent=`模型接收失败：${error.message}`;}});$('#worldLabel').textContent='🌿 三维全景 · 左键拖动 · 右键旋转 · 滚轮缩放';$('#drawer p').textContent='预设只生成起点。素材库包含任务目标；土块、食物、天敌、出生点和目标均可放置、选择、修改或删除。';renderPalette();predatorInfo();start();
