import * as THREE from '../node_modules/three/build/three.module.js';
import { MATERIALS, PLACEABLES, PREDATOR_LEVELS, PREDATOR_SPECIES, WORLD_PRESETS, createWorldPreset, normalizeWorld, validateWorld, resizeWorld, placeAsset, removeAt, assetLabel } from '../src/worldstudio.js';
import { ACTIONS, OBSERVATIONS, REWARD_EVENTS, TERMINATIONS, EXPERIMENT_PRESETS, RL_ALGORITHMS, createExperiment, NeuralRLSession } from '../src/neuralrl.js';
import { attachDeployment } from '../src/robotdeployment.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let world=createWorldPreset('meadow'),experiment=createExperiment('navigation'),session=null,running=false,generation=0,selectedAsset='voxel:rock',selectedEntityId=null,trace=[],trainedModelId=null,brainData=null;
try{const value=JSON.parse(localStorage.getItem('desktopFly.openTrainingProject.v1'));if(value){world=normalizeWorld(value.world);experiment={...createExperiment(),...value.experiment,traits:{...createExperiment().traits,...value.experiment?.traits}};}}catch{}
const save=()=>localStorage.setItem('desktopFly.openTrainingProject.v1',JSON.stringify({world,experiment}));
function download(value,name){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function num(id,fallback,min=-Infinity,max=Infinity){const el=$(id),v=Number(el.value),result=Number.isFinite(v)?Math.max(min,Math.min(max,v)):fallback;el.value=result;return result;}
function makeModelId(){const d=new Date(),pad=v=>String(v).padStart(2,'0'),stamp=`${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`,suffix=Math.random().toString(36).slice(2,6).toUpperCase();return `DFM-${stamp}-${suffix}`;}

// One editor renders the exact shared world contract used by ecology.
const canvas=$('#worldCanvas'),scene=new THREE.Scene();scene.background=new THREE.Color(0x07120f);scene.fog=new THREE.FogExp2(0x07120f,.026);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.shadowMap.enabled=true;
const camera=new THREE.PerspectiveCamera(44,1,.1,180),content=new THREE.Group(),pathGroup=new THREE.Group();scene.add(content,pathGroup,new THREE.HemisphereLight(0xcaf6df,0x12231b,1.55));
const sun=new THREE.DirectionalLight(0xe9ffef,2.2);sun.position.set(-10,18,-12);sun.castShadow=true;scene.add(sun);
let yaw=.72,pitch=.72,distance=28,pointerDown=null,previewSolids=new Set();const cameraTarget=new THREE.Vector3(0,2,0),trainingPredators=[];const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),materialCache=new Map();
canvas.dataset.worldNavigation='drag-orbit-zoom';canvas.dataset.predatorMotion='autonomous-collision';document.querySelector('.stage-label').textContent='3D 世界 · 左键点击放置/拖动世界 · 右键旋转 · 滚轮缩放';
function material(id){if(!materialCache.has(id)){const s=MATERIALS[id];materialCache.set(id,new THREE.MeshStandardMaterial({color:s.color,roughness:id==='water' ? .18 : .78,transparent:!s.solid,opacity:s.solid ? 1 : .7,emissive:(s.food||s.safe) ? s.color : 0,emissiveIntensity:(s.food||s.safe) ? .8 : 0}));}return materialCache.get(id);}
const cellPoint=p=>new THREE.Vector3(p.x-(world.size.x-1)/2,p.z,p.y-(world.size.y-1)/2);
function clear(group){while(group.children.length){const child=group.children[0];group.remove(child);child.traverse?.(node=>node.geometry?.dispose?.());}}
function entityModel(item){const group=new THREE.Group();let node;if(item.type==='spawn'){node=new THREE.Mesh(new THREE.RingGeometry(.28,.42,24),new THREE.MeshBasicMaterial({color:0x65e8df,side:THREE.DoubleSide}));node.rotation.x=-Math.PI/2;}else if(item.type==='goal'){node=new THREE.Mesh(new THREE.TorusGeometry(.36,.08,8,24),new THREE.MeshStandardMaterial({color:0xe6f769,emissive:0x799915,emissiveIntensity:1.5}));node.rotation.x=Math.PI/2;}else if(item.type==='food'){node=new THREE.Mesh(new THREE.SphereGeometry(.28,14,10),new THREE.MeshStandardMaterial({color:item.kind==='apple'?0xd94b3e:item.kind==='banana'?0xf0cc46:0xe79c35}));}else{node=new THREE.Mesh(item.kind==='spider'?new THREE.SphereGeometry(.34,12,9):new THREE.CapsuleGeometry(.24,.5,5,10),new THREE.MeshStandardMaterial({color:item.kind==='frog'?0x70a744:item.kind==='spider'?0x6f4735:0x91b94c,roughness:.65}));node.rotation.z=Math.PI/2;}group.add(node);group.userData.entityId=item.id;group.traverse(n=>n.userData.entityId=item.id);return group;}
function syncWorld(){ $('#headWorldSize').textContent=`${world.size.x}×${world.size.y}×${world.size.z}`;$('#projectTitle').textContent=world.name;$('#worldName').value=world.name;$('#sizeX').value=world.size.x;$('#sizeY').value=world.size.y;$('#sizeZ').value=world.size.z;$('#cellSize').value=world.cellSizeM;$('#friction').value=world.environment.friction;$('#wind').value=world.environment.wind;$('#light').value=world.environment.light;$('#editLayer').max=world.size.z-1;$('#editLayer').value=Math.min(Number($('#editLayer').value),world.size.z-1);$('#stageLayer').textContent=$('#editLayer').value;$('#layerValue').textContent=$('#editLayer').value; }
function rebuild(){clear(content);trainingPredators.length=0;previewSolids=new Set(world.voxels.filter(v=>MATERIALS[v[3]].solid).map(v=>`${v[0]},${v[1]},${v[2]}`));const ground=new THREE.Mesh(new THREE.PlaneGeometry(world.size.x+2,world.size.y+2),new THREE.MeshStandardMaterial({color:0x081a15,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.03;content.add(ground);const grid=new THREE.GridHelper(Math.max(world.size.x,world.size.y),Math.max(world.size.x,world.size.y),0x3c806a,0x163e32);grid.position.y=.01;content.add(grid);for(const [x,y,z,id] of world.voxels){const spec=MATERIALS[id],block=new THREE.Mesh(spec.solid?new THREE.BoxGeometry(.94,.94,.94):new THREE.CylinderGeometry(.3,.37,.12,16),material(id));block.position.copy(cellPoint({x,y,z}));block.position.y+=spec.solid?.47:.12;block.castShadow=spec.solid;block.receiveShadow=true;content.add(block);}for(const item of world.entities){if(!item.enabled)continue;const model=entityModel(item);model.position.copy(cellPoint(item.position));model.position.y+=.18;if(item.id===selectedEntityId)model.scale.setScalar(1.35);content.add(model);if(item.type==='predator')trainingPredators.push({model,item,x:item.position.x,y:item.position.y,z:item.position.z,heading:Math.random()*Math.PI*2,phase:Math.random()*10});}distance=Math.max(18,Math.max(world.size.x,world.size.y,world.size.z*2)*1.05);syncWorld();}
function renderPath(){clear(pathGroup);if(trace.length<2)return;const points=trace.map(p=>cellPoint(p).add(new THREE.Vector3(0,.3,0)));pathGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0x79f5ab,transparent:true,opacity:.85})));}
function setRay(event){const rect=canvas.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-((event.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(pointer,camera);}
function pickCell(event){setRay(event);const z=Number($('#editLayer').value),hit=new THREE.Vector3();if(!raycaster.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-z),hit))return null;const p={x:Math.round(hit.x+(world.size.x-1)/2),y:Math.round(hit.z+(world.size.y-1)/2),z};return p.x>=0&&p.y>=0&&p.x<world.size.x&&p.y<world.size.y?p:null;}
function pickEntity(event){setRay(event);return raycaster.intersectObjects(content.children,true).find(hit=>hit.object.userData.entityId)?.object.userData.entityId||null;}
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{pointerDown={x:e.clientX,y:e.clientY,button:e.button,pan:e.button===1||(e.button===0&&e.shiftKey),moved:false};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!pointerDown)return;if(Math.hypot(e.clientX-pointerDown.x,e.clientY-pointerDown.y)>4)pointerDown.moved=true;if(pointerDown.button===2){yaw-=e.movementX*.008;pitch=Math.max(.18,Math.min(1.38,pitch+e.movementY*.006));}else if(pointerDown.pan||(pointerDown.button===0&&pointerDown.moved)){const scale=distance*.0028,right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),forward=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw));cameraTarget.addScaledVector(right,-e.movementX*scale).addScaledVector(forward,e.movementY*scale);}});canvas.addEventListener('pointerup',e=>{if(pointerDown?.button===0&&!pointerDown.pan&&!pointerDown.moved){const entityId=pickEntity(e);if(entityId&&!selectedAsset){selectedEntityId=entityId;$('#statusText').textContent=`已选择 ${assetLabel(world.entities.find(v=>v.id===entityId))}，可以删除。`;rebuild();}else{const p=pickCell(e);if(p&&selectedAsset){world=selectedAsset==='erase'?removeAt(world,p):placeAsset(world,selectedAsset,p,{predatorLevel:$('#predatorLevel').value});selectedEntityId=null;world.name=$('#worldName').value||world.name;save();rebuild();}}}pointerDown=null;});canvas.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(8,Math.min(70,distance+e.deltaY*.015));},{passive:false});
function animateTrainingPredators(dt){let travel=0;for(const p of trainingPredators){const level=PREDATOR_LEVELS[p.item.level];p.phase+=dt;p.heading+=Math.sin(p.phase*.73)*dt*.7;const speed=level.speed*.28,nx=p.x+Math.cos(p.heading)*speed*dt,ny=p.y+Math.sin(p.heading)*speed*dt,cx=Math.round(nx),cy=Math.round(ny),blocked=cx<0||cy<0||cx>=world.size.x||cy>=world.size.y||previewSolids.has(`${cx},${cy},${p.z}`);if(blocked)p.heading+=Math.PI*(.55+Math.random()*.35);else{travel+=Math.hypot(nx-p.x,ny-p.y);p.x=nx;p.y=ny;}p.model.position.copy(cellPoint({x:p.x,y:p.y,z:p.z}));p.model.position.y+=.18;p.model.rotation.y=-p.heading;}canvas.dataset.predatorTravel=String(Number(canvas.dataset.predatorTravel||0)+travel);}
let lastFrame=performance.now();function frame(t){const dt=Math.min(.05,Math.max(0,(t-lastFrame)/1000));lastFrame=t;animateTrainingPredators(dt);const rect=canvas.getBoundingClientRect(),w=Math.max(1,Math.round(rect.width)),h=Math.max(1,Math.round(rect.height));if(canvas.width!==Math.round(w*renderer.getPixelRatio())||canvas.height!==Math.round(h*renderer.getPixelRatio())){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}const cp=Math.cos(pitch);camera.position.set(cameraTarget.x+Math.sin(yaw)*cp*distance,cameraTarget.y+Math.sin(pitch)*distance,cameraTarget.z+Math.cos(yaw)*cp*distance);camera.lookAt(cameraTarget);if(pathGroup.children[0])pathGroup.children[0].material.opacity=.55+Math.sin(t*.004)*.25;renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);

function renderPresets(){$('#worldPresets').replaceChildren(...WORLD_PRESETS.map(p=>{const b=document.createElement('button');b.className=`preset${world.preset===p.id?' active':''}`;b.innerHTML=`<b>${p.name}</b><span>${p.description}</span>`;b.onclick=()=>{if(running)return;world=createWorldPreset(p.id);selectedEntityId=null;trace=[];save();renderPresets();rebuild();renderPath();$('#statusText').textContent=`已生成${p.name}，现在所有内容都可以修改。`;};return b;}));$('#skillPresets').replaceChildren(...EXPERIMENT_PRESETS.map(p=>{const b=document.createElement('button');b.className=`preset${experiment.preset===p.id?' active':''}`;b.innerHTML=`<b>${p.name}</b><span>${p.id==='blank'?'从零组合全部规则':'载入后仍可任意增删规则'}</span>`;b.onclick=()=>{experiment=createExperiment(p.id);syncExperiment();renderPresets();save();};return b;}));}
function renderPalette(){const buttons=PLACEABLES.map(a=>{const b=document.createElement('button');b.textContent=a.name;b.classList.toggle('active',selectedAsset===a.id);b.onclick=()=>{selectedAsset=selectedAsset===a.id?null:a.id;selectedEntityId=null;renderPalette();$('#stageHelp').textContent=selectedAsset?`正在放置：${a.name}`:'选择模式：点击已有对象';};return b;});const erase=document.createElement('button');erase.textContent='删除格内全部';erase.classList.toggle('active',selectedAsset==='erase');erase.onclick=()=>{selectedAsset='erase';renderPalette();};$('#assetPalette').replaceChildren(...buttons,erase);}
function predatorInfo(){const level=PREDATOR_LEVELS[$('#predatorLevel').value];$('#predatorInfo').innerHTML=`<b>${level.name}天敌明确能力</b><br>${level.description}<br>移动 ${level.speed} 格/秒 · 冷却 ${level.cooldown} 秒 · 捕获率 ${Math.round(level.captureChance*100)}%<br>${Object.values(PREDATOR_SPECIES).map(s=>`${s.name}：${s.skills.map(v=>v.name).join('、')}`).join('<br>')}`;}
function renderChecks(){const build=(items,selected,target)=>{target.replaceChildren(...items.map(item=>{const label=document.createElement('label');label.className='check';label.innerHTML=`<input type="checkbox" value="${item.id}" ${selected.includes(item.id)?'checked':''} ${item.required?'disabled':''}>${item.name}`;return label;}));};build(OBSERVATIONS,experiment.observations,$('#observationList'));build(ACTIONS,experiment.actions,$('#actionList'));$$('#observationList input').forEach(el=>el.onchange=()=>{experiment.observations=$$('#observationList input:checked').map(v=>v.value);save();});$$('#actionList input').forEach(el=>el.onchange=()=>{experiment.actions=$$('#actionList input:checked').map(v=>v.value);if(!experiment.actions.length){el.checked=true;experiment.actions=[el.value];}save();});}
function renderRules(){$('#rewardRules').replaceChildren(...experiment.rewardRules.map((rule,index)=>{const row=document.createElement('div');row.className='rule';const select=document.createElement('select');for(const event of REWARD_EVENTS)select.add(new Option(event.name,event.id));select.value=rule.event;const input=document.createElement('input');input.type='number';input.step='.01';input.value=rule.weight;const del=document.createElement('button');del.textContent='×';select.onchange=()=>{rule.event=select.value;save();};input.onchange=()=>{rule.weight=Number(input.value);save();};del.onclick=()=>{experiment.rewardRules.splice(index,1);renderRules();save();};row.append(select,input,del);return row;}));}
function algorithmInfo(){const a=RL_ALGORITHMS.find(v=>v.id===$('#algorithm').value)||RL_ALGORITHMS[0];$('#algorithmInfo').textContent=`${a.family} · ${a.note}。观测进入感觉神经群，动作只从下降神经元活动读出；奖励通过多巴胺信号改变连接组增益。`;}
function syncExperiment(){if(!RL_ALGORITHMS.some(v=>v.id===experiment.algorithm))experiment.algorithm='three-factor';$('#experimentName').value=experiment.name;$('#episodes').value=experiment.episodes;$('#seed').value=experiment.seed;$('#maxSteps').value=experiment.maxSteps;$('#learningRate').value=experiment.learningRate;$('#gamma').value=experiment.gamma;$('#epsilon').value=experiment.epsilon;$('#normalizeReward').checked=experiment.normalizeReward;$('#speedTrait').value=experiment.traits.speed;$('#intelligenceTrait').value=experiment.traits.intelligence;$('#escapeTrait').value=experiment.traits.escapeSensitivity;$('#algorithm').value=experiment.algorithm;$('#successCondition').value=experiment.termination.success;$('#failureCondition').value=experiment.termination.failure;$('#terminationTarget').value=experiment.termination.target;renderChecks();renderRules();algorithmInfo();}
function readExperiment(){experiment.name=$('#experimentName').value.trim()||'未命名技能';experiment.episodes=num('#episodes',4000,100,100000);experiment.seed=num('#seed',42,1,999999);experiment.maxSteps=num('#maxSteps',240,20,3000);experiment.learningRate=num('#learningRate',.08,.001,1);experiment.gamma=num('#gamma',.97,0,.999);experiment.epsilon=num('#epsilon',.16,0,1);experiment.normalizeReward=$('#normalizeReward').checked;experiment.algorithm=$('#algorithm').value;experiment.termination={success:$('#successCondition').value,failure:$('#failureCondition').value,target:num('#terminationTarget',1,1,100000)};experiment.traits={speed:num('#speedTrait',1,.5,3),intelligence:num('#intelligenceTrait',1,.5,3),escapeSensitivity:num('#escapeTrait',1,.5,3)};save();return experiment;}
for(const a of RL_ALGORITHMS)$('#algorithm').add(new Option(`${a.name} · ${a.family}`,a.id));for(const t of TERMINATIONS){$('#successCondition').add(new Option(t.name,t.id));$('#failureCondition').add(new Option(t.name,t.id));}
$$('.step').forEach(b=>b.onclick=()=>{$$('.step').forEach(v=>v.classList.toggle('active',v===b));$$('.panel').forEach(v=>v.classList.toggle('active',v.dataset.panel===b.dataset.step));$('#inspectorTitle').textContent={world:'世界与素材',task:'技能规则',learn:'强化学习',deploy:'验证与部署'}[b.dataset.step];});
$('#editLayer').oninput=()=>{$('#stageLayer').textContent=$('#editLayer').value;$('#layerValue').textContent=$('#editLayer').value;if($('#exactZ'))$('#exactZ').value=$('#editLayer').value;};$('#predatorLevel').onchange=predatorInfo;$('#deleteSelected').onclick=()=>{if(!selectedEntityId){selectedAsset=null;renderPalette();$('#statusText').textContent='已进入选择模式。点击场景中的天敌、食物、出生点或目标，然后删除。';return;}world=removeAt(world,null,{entityId:selectedEntityId});selectedEntityId=null;save();rebuild();};
$('#resizeWorld').onclick=()=>{world=resizeWorld(world,{x:num('#sizeX',24,6,48),y:num('#sizeY',18,6,48),z:num('#sizeZ',10,3,20)});save();rebuild();renderPresets();};$('#worldName').onchange=()=>{world.name=$('#worldName').value.trim()||'自定义世界';world.preset='custom';save();syncWorld();};for(const [id,key] of [['#cellSize','cellSizeM'],['#friction','friction'],['#wind','wind'],['#light','light']])$(id).onchange=()=>{if(key==='cellSizeM')world.cellSizeM=num(id,.25,.01,10);else world.environment[key]=num(id,1,-20,20);save();};
$('#algorithm').onchange=()=>{const a=RL_ALGORITHMS.find(v=>v.id===$('#algorithm').value)||RL_ALGORITHMS[0];$('#algorithm').value=a.id;experiment.algorithm=a.id;$('#learningRate').value=a.defaults.learningRate;$('#gamma').value=a.defaults.gamma;$('#epsilon').value=a.defaults.epsilon;algorithmInfo();save();};$('#addRewardRule').onclick=()=>{experiment.rewardRules.push({id:`reward-${Date.now()}`,event:'step',weight:0,enabled:true});renderRules();save();};for(const id of ['#experimentName','#episodes','#seed','#maxSteps','#learningRate','#gamma','#epsilon','#normalizeReward','#speedTrait','#intelligenceTrait','#escapeTrait','#successCondition','#failureCondition','#terminationTarget'])$(id).onchange=readExperiment;
function metrics(){const s=session?.stats()||{episodes:0,recentSuccess:0,averageReward:0,collisions:0,caught:0};$('#metricEpisodes').textContent=s.episodes.toLocaleString('zh-CN');$('#metricTarget').textContent=`/ ${Number(experiment.episodes).toLocaleString('zh-CN')}`;$('#metricSuccess').textContent=`${Math.round(s.recentSuccess*100)}%`;$('#metricReward').textContent=s.averageReward.toFixed(2);$('#metricCollision').textContent=s.collisions.toLocaleString('zh-CN');$('#metricCaught').textContent=s.caught.toLocaleString('zh-CN');$('#trainProgress').style.width=`${Math.min(100,s.episodes/experiment.episodes*100)}%`;}
function stop(message){running=false;generation++;$('#trainButton').textContent='▶ 重新开始强化学习';$('#trainOverlay').classList.remove('show');$('#statusText').textContent=message;$('#evaluatePolicy').disabled=!session?.episodes;$('#exportPolicy').disabled=!session?.episodes;}
$('#trainButton').onclick=()=>{if(running){stop('训练已停止，当前神经模型保留。');return;}if(!brainData?.circuit?.edges?.length){$('#statusText').textContent='无法训练：尚未加载完整 FlyWire 突触数据。';return;}readExperiment();const check=validateWorld(world);if(!check.valid){$('#statusText').textContent=`无法训练：${check.errors.join('；')}`;return;}if(!experiment.rewardRules.length){$('#statusText').textContent='至少添加一条奖励或惩罚规则。';return;}trainedModelId=null;session=new NeuralRLSession(world,experiment,brainData);trace=[];renderPath();metrics();running=true;const token=++generation;$('#trainButton').textContent='■ 停止神经强化学习';$('#trainOverlay').classList.add('show');$('#statusText').textContent=`正在训练 ${brainData.circuit.neurons.length} 神经元 / ${brainData.circuit.edges.length} 突触的连接组控制器；身体动作只能由下降神经元和 MaleCNS 产生。`;const batch=()=>{if(!running||token!==generation)return;let latest;for(let i=0;i<Math.max(2,Math.min(12,Math.round(experiment.episodes/160)))&&session.episodes<experiment.episodes;i++)latest=session.trainEpisode();if(latest){trace=latest.trace;renderPath();}metrics();const s=session.stats();$('#trainState').textContent=`${session.episodes}/${experiment.episodes} 回合 · 多巴胺 ${s.meanAbsoluteDopamine.toFixed(4)} · 已改变 ${s.changedGroupEdges} 组突触`;if(session.episodes<experiment.episodes)setTimeout(batch,4);else{running=false;trainedModelId=makeModelId();const result=session.evaluate();$('#trainButton').textContent='↻ 使用当前规则重训';$('#trainOverlay').classList.remove('show');$('#evaluatePolicy').disabled=false;$('#exportPolicy').disabled=false;$('#statusText').textContent=`训练完成。模型编号 ${trainedModelId}；${s.brainNeurons} 神经元、${s.brainEdges} 突触，${s.changedGroupEdges} 个连接组发生可塑变化；评估${result.success?'成功':'未达条件'}。`;$('#deploymentStatus').textContent=`神经模型 ${trainedModelId} · ${session.episodes.toLocaleString('zh-CN')} 回合 · 连接组指纹和突触增益已封装，可部署到指定果蝇。`;}};setTimeout(batch,10);};
$('#resetTraining').onclick=()=>{session=null;trace=[];renderPath();metrics();stop('训练状态已清空，世界与规则没有改变。');};$('#evaluatePolicy').onclick=()=>{const r=session.evaluate();trace=r.trace;renderPath();$('#statusText').textContent=`评估：${r.success?'成功':'失败'} · 奖励 ${r.totalReward.toFixed(2)} · 碰撞 ${r.collisions} · ${r.caught?'被捕获':'未被捕获'}`;};
function deploymentManifest(){const manifest=attachDeployment(session.exportManifest(experiment.name),{robotType:$('#robotType').value,maxLinear:num('#maxLinear',.45,.01,5),safeDistance:num('#safeDistance',.28,.05,10),commandTopic:$('#commandTopic').value,emergencyStopTopic:$('#estopTopic').value,mapResolution:world.cellSizeM});manifest.modelId=trainedModelId||(trainedModelId=makeModelId());manifest.displayName=`${manifest.name} · ${manifest.modelId}`;return manifest;}
async function publishPolicy({downloadCopy=false,openEcology=false}={}){if(!session?.episodes){$('#deploymentStatus').textContent='请先完成训练，再部署到生态果蝇。';return;}try{const manifest=deploymentManifest();await window.flyAPI.saveOpenPolicy(manifest);localStorage.setItem('desktopFly.latestPolicySummary.v1',JSON.stringify({modelId:manifest.modelId,name:manifest.name,episodes:manifest.metrics.episodes,createdAt:manifest.createdAt}));if(downloadCopy)download(manifest,`${manifest.modelId}-${manifest.name.replace(/\s+/g,'-')}.policy.json`);$('#deploymentStatus').textContent=`✅ 模型 ${manifest.modelId} 已保存${downloadCopy?'，备份文件名也包含该编号':''}。`;if(openEcology)window.flyAPI.showWindow('ecosystem');}catch(error){$('#deploymentStatus').textContent=`部署准备失败：${error.message}`;}}
$('#exportWorld').onclick=()=>download(world,`${world.name.replace(/\s+/g,'-')}.world.json`);$('#exportPolicy').onclick=()=>publishPolicy({downloadCopy:true});
$('#importProject').onclick=()=>$('#projectFile').click();$('#projectFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const value=JSON.parse(await file.text());world=normalizeWorld(value.world||value);if(value.experiment)experiment={...createExperiment(),...value.experiment,traits:{...createExperiment().traits,...value.experiment.traits}};session=null;trace=[];save();renderPresets();syncExperiment();rebuild();renderPath();metrics();$('#statusText').textContent='工程已导入。世界与全部强化学习规则均可继续修改。';}catch(error){$('#statusText').textContent=`导入失败：${error.message}`;}e.target.value='';};
$('#newBlank').onclick=()=>{world=createWorldPreset('blank');experiment=createExperiment('blank');session=null;trace=[];save();renderPresets();syncExperiment();rebuild();renderPath();metrics();};$('#openEcosystem').onclick=()=>session?.episodes?publishPolicy({openEcology:true}):window.flyAPI.showWindow('ecosystem');$('#openEcology').onclick=()=>publishPolicy({openEcology:true});$('#openDeployGuide').onclick=()=>{$('#deploymentStatus').textContent='训练完成 → 直接部署到生态空间 → 选择果蝇并确认部署；真机则继续进行 PyBullet 和 ROS 2 验证。';};
$('#exportPolicy').textContent='保存模型并导出备份';$('#openEcology').textContent='直接部署到生态果蝇';
const exactPlacement=document.createElement('div');exactPlacement.className='field';exactPlacement.innerHTML='<label>精确坐标放置（所有素材支持高度 Z）</label><div class="three"><input id="exactX" type="number" min="0" value="2" aria-label="放置X"><input id="exactY" type="number" min="0" value="2" aria-label="放置Y"><input id="exactZ" type="number" min="0" value="1" aria-label="放置Z"></div><button class="secondary" id="placeExact" style="margin-top:6px">放置当前素材到 X / Y / Z</button>';$('#predatorLevel').closest('.field').before(exactPlacement);$('#placeExact').onclick=()=>{if(!selectedAsset||selectedAsset==='erase'){$('#statusText').textContent='请先从素材库选择要放置的方块、目标、食物或天敌。';return;}const p={x:Number($('#exactX').value),y:Number($('#exactY').value),z:Number($('#exactZ').value)};if(!Number.isInteger(p.x)||!Number.isInteger(p.y)||!Number.isInteger(p.z)||p.x<0||p.y<0||p.z<0||p.x>=world.size.x||p.y>=world.size.y||p.z>=world.size.z){$('#statusText').textContent=`坐标超出世界范围：X 0–${world.size.x-1}，Y 0–${world.size.y-1}，Z 0–${world.size.z-1}。`;return;}const next=placeAsset(world,selectedAsset,p,{predatorLevel:$('#predatorLevel').value});const check=validateWorld(next);if(!check.valid){$('#statusText').textContent=`不能放置：${check.errors.join('；')}`;return;}world=next;save();rebuild();$('#editLayer').value=p.z;$('#editLayer').dispatchEvent(new Event('input'));$('#statusText').textContent=`已把 ${PLACEABLES.find(item=>item.id===selectedAsset)?.name||'素材'} 放到 (${p.x}, ${p.y}, ${p.z})。`;};
renderPresets();renderPalette();predatorInfo();syncExperiment();rebuild();metrics();
window.flyAPI.getBrainData().then(value=>{brainData=value;if(!value?.circuit?.edges?.length)throw new Error('circuit.json 不完整');document.querySelector('.base b').textContent=`FlyWire v783 ${value.circuit.neurons.length}n/${value.circuit.edges.length}e + MaleCNS ${value.locomotor?.neurons?.length||0}n`;$('#statusText').textContent='真实连接组已加载。观测会进入感觉神经群，奖励将改变可塑突触，动作经下降神经元和 MaleCNS 输出。';}).catch(error=>{$('#statusText').textContent=`神经模型加载失败：${error.message}`;$('#trainButton').disabled=true;});
